# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "[python] "
    open-pull-requests-limit: 10
    groups:
      compatible:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependabot"
      - "dependencies"
    assignees:
      - afonasev

  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: monthly
    commit-message:
      prefix: "[docker] "
    labels:
      - "dependabot"
    assignees:
      - afonasev

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "[actions] "
    labels:
      - "dependabot"
    assignees:
      - afonasev
