---
# https://github.com/marketplace/actions/github-labeler
name: Manage labels

on:
    push:
        branches:
            - main
        paths:
            - .github/labels.yaml
            - .github/workflows/labels.yaml
    pull_request:
        paths:
            - .github/labels.yaml
            - .github/workflows/labels.yaml

jobs:
    labeler:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Run Labeler
              uses: crazy-max/ghaction-github-labeler@v5
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  yaml-file: .github/labels.yaml
                  dry-run: ${{ github.event_name == 'pull_request' }}
                  exclude: |
                      help*
                      *issue
